apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: {{ .Release.Namespace }}-channel
spec:
  pathname: {{ .Values.git.repository }} 
  secretRef:
    name: {{ .Values.git.secret }} 
  type: HelmRepo 
