apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-placement
spec:
  clusterSelector:
    matchLabels:
      app-target: {{ .Release.Namespace }}
