apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: charts/remote
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-subscription
spec:
  channel: {{ .Release.Namespace }}/{{ .Release.Namespace }}-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: {{ .Release.Namespace }}/{{ .Release.Namespace }}-placement
