apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: lamp-integration-channel
spec:
  pathname: https://github.com/poc-ocp-0321/ansible-lamp.git
  secretRef:
    name: github-poc-ocp-0321
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: manifests/overlays/integration
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: lamp-integration
  name: lamp-integration-subscription
spec:
  channel: lamp-integration/lamp-integration-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: lamp-integration-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: lamp-integration
  name: lamp-integration-placement
spec:
  clusterSelector:
    matchLabels:
      namespace-lamp-integration: deploy
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ""
    apps.open-cluster-management.io/subscriptions: lamp-test1-subscription
  name: lamp-integration
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - lamp-integration
