kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: oc-virtctl
  labels:
    build: oc-virtctl
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'oc-virtctl:latest'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'ubi:latest'
  source:
    type: Dockerfile
    dockerfile: >-
      FROM registry.access.redhat.com/ubi7/ubi

      RUN curl -O https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.2/openshift-client-linux-4.7.2.tar.gz
      && tar zxvf openshift-client-linux-4.7.2.tar.gz
      && mv oc /usr/bin/oc
      && rm -rf openshift-client-linux-4.7.2.tar.gz
      && chmod +x /usr/bin/oc

      RUN curl -O https://github.com/kubevirt/kubevirt/releases/download/v0.39.0/virtctl-v0.39.0-linux-amd64 -L
      && mv virtctl-v0.39.0-linux-amd64 /usr/bin/virtctl
      && chmod +x /usr/bin/virtctl

      USER 1001
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: tower-cli
  labels:
    build: tower-cli
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'tower-cli:latest'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'python-36:latest'
  source:
    type: Dockerfile
    dockerfile: >-
      FROM registry.access.redhat.com/ubi8/python-36

      RUN pip install ansible-tower-cli

      USER 1001
