- name: Set VM conf 
  template:
    src: "files/vm-config.yaml.j2"
    dest: "/tmp/vm-config.yaml"

- name: Set VM create script
  template:
    src: "files/create-vm.sh"
    dest: "/tmp/create-vm.sh"    

- name: create vm php 1
  shell: "sh /tmp/create-vm.sh {{ prefix }}-php-1 {{ prefix }}-php"
  
- name: create vm php 2
  shell: "sh /tmp/create-vm.sh {{ prefix }}-php-2 {{ prefix }}-php"
  
- name: create vm bdd
  shell: "sh /tmp/create-vm.sh {{ prefix }}-bdd {{ prefix }}-bdd"

