- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - httpd
      - php
      - php-mysqli
      - php-pdo 
      - php-gd 
      - php-odbc 
      - php-pear 
      - php-xml 
      - php-xmlrpc 
      - php-soap
      - php-mbstring
      - php-mysqlnd
      
- name: Create apache group
  group:
    name: "{{ login_apache_user }}"
    state: present

- name: Create the apache user
  user:
    name: "{{ login_apache_user }}" 
    shell: /bin/bash
    groups: "{{ login_apache_user }}"
    comment: Apache User
    password: "{{ passwd_apache_user }}"

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ login_apache_user }}"
    mode: '0755'

- name: Set up Apache conf 
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"

- name: Set up Apache virtualhost
  template:
    src: "files/host.conf.j2"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"

# PHP Info Page
- name: Sets Up PHP Info Page
  template:
    src: "files/info.php.j2"
    dest: "/var/www/{{ http_host }}/info.php"
    
- name: Sets Up PHP FPM conf
  template:
    src: "files/fpm.conf"
    dest: "/etc/php-fpm.d/www.conf"
    
- name: Reload Fpm
  service:
    name: php-fpm 
    state: reloaded

- name: Restart Fpm
  service:
    name: php-fpm
    state: restarted
    
- name: Reload Apache
  service:
    name: httpd 
    state: reloaded

- name: Restart Apache
  service:
    name: httpd
    state: restarted
