- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - httpd
      - php
      - php-mysqli
      - php-pdo 
      - php-gd 
      - php-odbc 
      - php-pear 
      - php-xml 
      - php-xmlrpc 
      - php-soap

- name: Create apache group
  group:
    name: "{{ login_apache_user }}"
    state: present

- name: Create the apache user
  user:
    name: "{{ login_apache_user }}" 
    shell: /bin/bash
    groups: "{{ login_apache_user }}"
    comment: Apache User
    password: "{{ passwd_apache_user }}"

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ login_apache_user }}"
    mode: '0755'

- name: Set up Apache conf 
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"

- name: Set up Apache virtualhost
  template:
    src: "files/host.conf.j2"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"

# PHP Info Page
- name: Sets Up PHP Info Page
  template:
    src: "files/info.php.j2"
    dest: "/var/www/{{ http_host }}/info.php"

- name: Reload Apache
  service:
    name: httpd 
    state: reloaded

- name: Restart Apache
  service:
    name: httpd
    state: restarted
    
- name: Install required packages php55
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - php-gd
      - php-mbstring
      - php-mysqlnd  
  
- name: update files php55
  shell: "mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php54.off; mv /etc/httpd/conf.modules.d/10-php.conf /etc/httpd/conf.modules.d/10-php54.off; cp /opt/rh/httpd24/root/etc/httpd/conf.d/php55-php.conf /etc/httpd/conf.d/; cp /opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-php55-php.conf /etc/httpd/conf.modules.d/; cp /opt/rh/httpd24/root/etc/httpd/modules/libphp55-php5.so /etc/httpd/modules/"

- name: Restart Apache
  service:
    name: httpd
    state: restarted
