- name: Set VM create script
  template:
    src: "files/install-vm.sh"
    dest: "/tmp/install-vm.sh"    

- name: install vm php 1
  shell: "sh /tmp/install-vm.sh {{ prefix }}-php-1 poc-php mysql_server={{ prefix }}-bdd"
  register: _install_vm1
  async: 600  # Maximum runtime in seconds. Adjust as needed.
  poll: 0  # Fire and continue (never poll)
  
- name: install vm php 2
  shell: "sh /tmp/install-vm.sh {{ prefix }}-php-2 poc-php mysql_server={{ prefix }}-bdd"
  register: _install_vm2
  async: 600  # Maximum runtime in seconds. Adjust as needed.
  poll: 0  # Fire and continue (never poll)
  
- name: install vm bdd
  shell: "sh /tmp/install-vm.sh {{ prefix }}-bdd poc-bdd"
  register: _install_vm3
  async: 600  # Maximum runtime in seconds. Adjust as needed.
  poll: 0  # Fire and continue (never poll)

- name: wait for all 3 tasks
  async_status: jid="{{ item }}"
  register: job_result
  until: job_result.finished
  retries: 300
  with_items:
        - "{{ _install_vm1.ansible_job_id }}"
        - "{{ _install_vm2.ansible_job_id }}"
        - "{{ _install_vm3.ansible_job_id }}"  
