apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: images-channel
spec:
  pathname: https://github.com/poc-ocp-0321/ansible-lamp.git
  secretRef:
    name: github-poc-ocp-0321
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: manifests/overlays/images
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: images
  name: images-subscription
spec:
  channel: images/images-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: images-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: images
  name: images-placement
spec:
  clusterSelector:
    matchLabels:
      namespace-images: deploy
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ""
    apps.open-cluster-management.io/subscriptions: images-subscription
  name: images
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - images
