kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registry-viewer
subjects:
  - kind: ServiceAccount
    namespace: lamp-integration
    name: pipeline
  - kind: ServiceAccount
    namespace: casdusage1
    name: default
  - kind: ServiceAccount
    namespace: serverless-images
    name: builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-viewer
