apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: starter
  name: starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: starter
    spec:
      initContainers:
          - name: oc-virtctl
            image: image-registry.openshift-image-registry.svc:5000/images/oc-virtctl
          - name: tower-cli
            image: image-registry.openshift-image-registry.svc:5000/images/tower-cli
      containers:
          - name: starter
            image: registry.access.redhat.com/ubi7/ubi
            command: ["sh", "-c", "tail -f /dev/null"]
      restartPolicy: Always
